name: Commit request Workflow

on:
  - commit

jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: linux install
        uses: scottbrenner/cfn-lint-action@v2
        with:
          command: cfn-lint -t ./VPC-Creation.yaml